version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: SuReview_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: SuReview_db
    volumes:
      - ./data:/data/db